### PR TITLE
Add JP's bio

### LINKED ISSUE #1: JP's bio is missing

### PR DESCRIPTION
**Pull request by jungaretti**
Closes #1

### CODE REVIEW

**Comment by thok-shock** [comment]
i don't know how i feel about this

**Comment by ophunt** [comment]
I'm strongly in favor, @thok-shock what part of this are you uncomfortable with? Kinda sus tbh ngl

**Comment by baileyconradt** [comment]
definitely sus, I say we vote off @thok-shock and approve the request

**Review by ophunt — APPROVED** [review]
Looks like a great bio JP, thanks for your contribution!

**Review by thok-shock — CHANGES_REQUESTED** [review]
Please update Chipotle to Qdoba - Chipotle has a lot of issues with food poisoning.

- [x] Find a better restaurant

**Comment by ophunt** [comment]
@baileyconradt please submit your review we are on a tight deadline the client will not be happy

**Comment by jungaretti** [comment]
Closes #1

**Review by baileyconradt — APPROVED** [review]
looks good, our client Luna will be happy

**Pull request merged**
